### ISSUE TITLE
Decide on Pull Request policy

### ISSUE THREAD

**Issue by modkaffes** [universelabs/universe-webapp#12]
As we’re using AVH edition of git-flow, it’s a bit unclear on how we’re utilizing Pull Requests in our dev flow. Let’s discuss and decide.

**Comment by guylepage3** [comment]
@modkaffes I'm closing this issue as it should already be defined in the Contribution Guidelines. https://github.com/universelabs/universe/blob/master/CONTRIBUTING.md
