### ISSUE TITLE
Need to remove user's email address from URL string

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#14]
**Describe the bug**
Need to remove user's email address from URL string.

**To Reproduce**
1. Sign up and/or go to dashboard and look at the URL, you'll see the user's email address included in the URL string.
  i. https://universe-webapp.herokuapp.com/dashboard?user=gusbergeralsdjfklsdjfkas@gmail.com

**Expected behavior**
User should only see https://app.universe.engineering/dashboard as the URL string.

**Screenshot**
![image](https://user-images.githubusercontent.com/1711854/59850466-4f560580-9338-11e9-8209-a466a2cd1fda.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5 (18F203)
- Brave Browser
- Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)

**Comment by modkaffes** [comment]
This was solved after implementing client side auth. Now JWT auth is used to identify the user.
