### ISSUE TITLE
Appended email address sign up error on local environment

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#15]
**Describe the bug**
Appended email address sign up error on local environment.

```
NOTE:  ! -- NOT A PRIORITY. LOCAL ENV ISSUE ONLY -- !
```

**To Reproduce**
1. Run the app locally
2. Try signing up with an appended gmail email address. ie. guylepage3+appendname@gmail.com.
3. User is taken to the Universe App Error page.

**Expected behavior**
1. Run the app locally
2. Try signing up with an appended gmail email address. ie. guylepage3+appendname@gmail.com.
3. User is taken to the dashboard with the correct credentials appearing.

**Screenshots**
![image](https://user-images.githubusercontent.com/1711854/59852250-7282b400-933c-11e9-966a-6ce073a81f5d.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5 (18F203)
 - Brave Browser
 - Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)

**Comment by guylepage3** [comment]
@modkaffes this is a local env issue only. Not priority.

**Comment by modkaffes** [comment]
Fixed
