### ISSUE TITLE
Appended email string missing `+` symbol

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#16]
**Describe the bug**
Appended email string missing `+` symbol.

**To Reproduce**
1. Create a user acccount with an appended gmial email address. ie. `guylepage3+append@gmail.com`
2. Once on dashboard, you'll see that the `+` symbol is missing with a space in between the main email content and the appended email content. ie `guylepage3 append@gmail.com`

**Expected behavior**
User should see the `+` symbol  between the main email content and the appended email content. ie `guylepage3+append@gmail.com`

**Screenshots**
<img width="400" alt="Screenshot 2019-06-20 09 22 47" src="https://user-images.githubusercontent.com/1711854/59852771-87ac1280-933d-11e9-9d6b-82f174fdc006.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5 (18F203)
- Brave Browser
- Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)

**Comment by guylepage3** [comment]
Working on this now..

**Comment by guylepage3** [comment]
Removing myself from this issue.. Need to focus on fundraising.. Leaving this to you two @modkaffes @dantrevino

**Comment by modkaffes** [comment]
Fixed
