### ISSUE TITLE
User is unable to log out of app

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#18]
**Describe the bug**
User is unable to log out of app.

**To Reproduce**
1. Go to https://app.universe.engineering/signin.
2. Enter credentials and log in. 
3. Click "Log out" in the navigation.
4. Nothing happens.

**Expected behavior**
1. Go to https://app.universe.engineering/signin.
2. Enter credentials and log in. 
3. Click "Log out" in the navigation.
4. User should be logged out of the app and land on a page letting them know that they've successfully logged out.

**Comment by modkaffes** [comment]
This was solved by implementing proper authentication.
