### ISSUE TITLE
Data latency is too much. Need to move data to a faster provider

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#20]
**Describe the bug**
Data latency is too much. Need to move data to a faster provider.

**To Reproduce**
1. Spinner takes too long on the dashboard before populating ids.

**Expected behavior**
Zero latency.

**Comment by guylepage3** [comment]
@modkaffes let's go with Digital Ocean or https://cloud.mongodb.com

**Comment by guylepage3** [comment]
You should have credentials for those.

**Comment by modkaffes** [comment]
This is irrelevant by now as the mock data is fetched by local db.
