### ISSUE TITLE
Update html title for dashboard

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#31]
### Universe v0.2 Alpha Demo Product Review (Sprint 5)
[›› Issue List from Product Review](https://github.com/universelabs/universe-webapp/issues/26)

----

**Description**
It will be a better UX to change the dashboard html title to something like: `dashboard`

**Reference(s)**
- [Update meta data title for dashboard](https://github.com/universelabs/universe-marketing/issues/14)

**Screenshots**
Current view

![image](https://user-images.githubusercontent.com/1711854/60306490-5b306180-990e-11e9-8e4d-c291d708f873.png)

**Comment by modkaffes** [comment]
If there’s no objection, I’ll also add ` - Universe` to each page’s title, for brand awareness.

**Comment by guylepage3** [comment]
@modkaffes, That's fine. 👍

**Comment by guylepage3** [comment]
@modkaffes do you want to bang this one out really quick?

**Comment by guylepage3** [comment]
Moving issue to [Sprint 6](https://github.com/orgs/universelabs/projects/7).
