### ISSUE TITLE
Add README instructions on how to run webapp locally

### ISSUE THREAD

**Issue by modkaffes** [universelabs/universe-webapp#39]

**Comment by guylepage3** [comment]
Nice work @modkaffes. Made a few revisions but other than that reads well. 👍

**Comment by guylepage3** [comment]
One of the requirements for running the web app is to run the auth server as well. I noticed that the auth server documentation has not been updated. Pinning the new auth server documentation issue here. 

[#11 Update README documentation for running server](https://github.com/universelabs/universe-auth/issues/11)
