### ISSUE TITLE
Alpha Demo App Use Case Instructions v2

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#44]
**Description**
In designing the new on-boarding screens, we discovered this issue is not our product but explaining to others how to use other products, ie. Blockstack. This is something beyond our control and we should not include instructions within our application on how to use other folks products.

As a result we need to create "Alpha Demo App Use Case Instructions." 

**Tasks**
- [x] Create "Alpha Demo App Use Case Instructions." 

**References**
- [#28 Design new on-boarding views](https://github.com/universelabs/universe-design2/issues/21)
- [#50 Alpha Demo App Use Case Instructions v1](https://github.com/universelabs/universe-operations2/issues/42)

**Comment by guylepage3** [comment]
**A real world use case for Universe today**
- Use Universe to Recover your Blockstack account.
  - Visit a Blockstack DApp (https://note.riot.ai).
  - Open a new tab on your browser and login to your Universe Account (https://app.universe.engineering/).
  - Click on your "Blockstack Recovery Phrase".
  - Click “Login” on the Note Riot (Blockstack) DApp (https://note.riot.ai) and sign in with an existing ID by pasting your Blockstack Recovery Phrase.

**Comment by guylepage3** [comment]
@dantrevino @itamarreif @modkaffes @faddat @aseoconnor @pftchal  please let me know if there's anything you catch on these v2 instructions. Thank you.

**Comment by aseoconnor** [comment]
A real-world use case for Universe today:

- Use the [Universe Alpha Demo](https://app.universe.engineering) to **Create** or **Recover** your Blockstack account. 
- [Login](https://app.universe.engineering/login) to your Universe Account. Click on your "**Blockstack Recovery Phrase**" to copy it to your clipboard. 
- Visit a Blockstack DApp like [NoteRiot](https://note.riot.ai).
- Sign in to NoteRiot with the ID you just copied.

**Comment by guylepage3** [comment]
@aseoconnor Great reduction in the set! ❤️ 

Here's a bit more of a change as we do not want to confuse the user and discuss Blockstack account creation. It's possible, yes, but not for this demo.

#### WISYWIG Link Version

- Use the [**Universe Alpha Demo**](https://app.universe.engineering) to **Recover** your Blockstack account. 
- [**Login**](https://app.universe.engineering/) to your Universe Account. Click on your "**Blockstack Recovery Phrase**" to copy it to your clipboard. 
- Visit a Blockstack DApp like [**NoteRiot**](https://note.riot.ai).
- Sign in to NoteRiot with the ID you just copied to your clipboard.

#### Full URL Link Version

- Use the **Universe Alpha Demo** (https://app.universe.engineering) to **Recover** your Blockstack account. 
- **Login** (https://app.universe.engineering/) to your Universe Account. Click on your "**Blockstack Recovery Phrase**" to copy it to your clipboard. 
- Visit a Blockstack DApp like NoteRiot (https://note.riot.ai).
- Sign in to NoteRiot with the ID you just copied to your clipboard.

**Comment by guylepage3** [comment]
@aseoconnor I included as second set with links in full as these instructions may be sent out in various ways.

**Comment by aseoconnor** [comment]
looks good!


Best,

Sean
SeanOConn.org
@aseoconnor <http://twitter.com/aseoconnor>

**Comment by guylepage3** [comment]
Cool! Closing this issue folks. Please reopen it if you think or find anything.
