### ISSUE TITLE
Customer journey for Alpha Demo w/ Feather device v0.3.0

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#46]
**Description**
Customer journey for Alpha Demo w/ Feather device v0.3.0 (workflows).

**Tasks**
- [x] Write out detailed New Universe User Feather Device Workflow
- [x] Write out detailed Existing Universe User Feather Device Workflow

**User Flow**
The following is a user flow that @itamarreif and @guylepage3 worked out yesterday (Jul 29, 2019) which takes into account the migration of users from the Alpha Demo Web App v0.2.0.

[2019-07-29 User flow.pdf](https://github.com/universelabs/universe-webapp/files/3448025/2019-07-29.User.flow.pdf)

**Reference**
- Google Doc for comments - https://docs.google.com/document/d/16werS5rmD2-P0u-4RKOeg8U9PybpQ-5CqHcTenSFDAQ/edit?usp=sharing

**Comment by guylepage3** [comment]
## 1. New Universe User Feather Device Workflow
1. User opens device packaging
2. User sees card that reads... 
    - "Universe Feather" [medium size type].
    - "Designed with love by Universe" [small type].
3. User picks up card and sees the Universe Feather device underneath card.
4. User looks on back to see setup instructions. **Back Side of card reads**....
    - [Universe icon] + [Bluetooth icon].
    - [Headline] "Connect your Universe Feather to your laptop" [bold type].
    - "Requirements: To use the Alpha Demo Feather Device you'll be required to connect to a Bluetooth enabled laptop with Chrome or Brave browser installed.
    - "1. To connect to your laptop open your web browser on your laptop and go to" [bold type].
    - "app.universe.engineering/feather"
5. User opens their Chrome or Brave browser, navigates, and sees a welcome landing page that reads... 
    - [Universe logo]
    - "Welcome to Universe"
    - "Your Universe Feather device is not connected." [bold type]
    - "Please follow the setup instructions on that came with your device or **click here** for instructions."
6. User chooses to read **paper instructions** or clicks to read **online instructions**

### Paper Instruction Path
7. User chooses to read paper instructions
    - "2. Turn on device" — ›››››› [[[[[ This is an unknown ]]]]] ‹‹‹‹‹‹ —
    - "Press the button to turn on Universe Feather device"
    - "3. Connect device"
    - "Go to your Bluetooth setting and choose Feather Device"
    - "4. Sign up"
    - "Go back to your web browser and sign up for Universe"
8. User goes back to web browser and sees...
    - [Connected icon]
    - "Connected"
    - "Your Universe Feather device is now connected. Please sign up for Universe."
    - [Sign up form]

### Online Instruction Path
7. User chooses to read online instructions
    - [Universe icon] + [Bluetooth icon]
    - [Headline] "Connect your Universe Feather to your laptop" [bold type].
    - "Turn on device" — ›››››› [[[[[ This is an unknown ]]]]] ‹‹‹‹‹‹ —
    - "Press the button to turn on Universe Feather device"
    - "Connect device"
    - "Go to your Bluetooth setting and choose Feather Device"
    - "Sign up"
    - "Go back to your web browser and sign up for Universe"
8. User is automatically redirected to sign up view...
    - [Connected icon]
    - "Connected"
    - "Your Universe Feather device is now connected. Please sign up for Universe."
    - [Sign up form]

**Comment by guylepage3** [comment]
## 2. Existing Universe User Feather Device Workflow
1. User opens device packaging
2. User sees card that reads... 
    - "Universe Feather" [medium size type].
    - "Designed with love by Universe" [small type].
3. User picks up card and sees the Universe Feather device underneath card.
4. User looks on back to see setup instructions. **Back Side of card reads**....
    - [Universe icon] + [Bluetooth icon].
    - [Headline] "Connect your Universe Feather to your laptop" [bold type].
    - "Requirements: To use the Alpha Demo Feather Device you'll be required to connect to a Bluetooth enabled laptop with Chrome or Brave browser installed.
    - "1. Log in to your Universe account
    - "Navigate to app.universe.engineering and log in using your existing Universe account."
    - 2. To connect to your laptop open your web browser on your laptop and go to" [bold type].
    - "app.universe.engineering/pair"
5. User opens their Chrome or Brave browser, navigates, and sees a welcome landing page that reads... 
    - [Universe logo]
    - "Welcome to Universe"
    - "Your Universe Feather device is not connected." [bold type]
    - "Please follow the setup instructions on that came with your device or **click here** for instructions."
6. User chooses to read **paper instructions** or clicks to read **online instructions**

### Paper Instruction Path
7. User chooses to read paper instructions
    - "3. Turn on device" — ›››››› [[[[[ This is an unknown ]]]]] ‹‹‹‹‹‹ —
    - "Press the button to turn on Universe Feather device"
    - "4. Connect device"
    - "Go to your Bluetooth setting and choose Feather Device"
    - "5. Confirm device"
    - "Go back to your web browser and confirm device"
8. User goes back to web browser and sees...
    - [Connected icon]
    - "Connected"
    - "Your Universe Feather device is now connected. Please confirm your Universe Feather device by entering your password."
    - [Password form field]

### Online Instruction Path
7. User chooses to read online instructions
    - [Universe icon] + [Bluetooth icon]
    - [Headline] "Connect your Universe Feather to your laptop" [bold type].
    - "Turn on device" — ›››››› [[[[[ This is an unknown ]]]]] ‹‹‹‹‹‹ —
    - "Press the button to turn on Universe Feather device"
    - "Connect device"
    - "Go to your Bluetooth setting and choose Feather Device"
    - "Confirm device"
    - "Go back to your web browser and confirm device"
8. User is automatically redirected to confirm view...
    - [Connected icon]
    - "Connected"
    - "Your Universe Feather device is now connected. Please confirm your Universe Feather device by entering your password."
    - [Password form field]

**Comment by itamarreif** [comment]
Looks good!

**Comment by guylepage3** [comment]
Cool. Closing issue
