### ISSUE TITLE
Bluetooth Javascript client

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#51]
**Description**
Bluetooth Javascript client

**Comment by modkaffes** [comment]
@itamarreif I created a hook to handle feather bluetooth connection. Work is in progress in [feature/feather-workflows](https://github.com/universelabs/universe-webapp/tree/feature/feather-workflows) and you can find the specific part [here](https://github.com/universelabs/universe-webapp/blob/85c03bd3885267c762d942a1d128515a7bdbaa1d/client/src/hooks/useBTConnected.js#L11).

As I’m not very up-to-date with Web Bluetooth API, I just created the hook as a placeholder where you can add your connections using native js. We probably have to persist whether the device is connected or not to localStorage(?). Take a look and ping me with questions.

**Comment by itamarreif** [comment]
This is deprecated due to Google's abandonment of the Web Bluetooth project.
