### ISSUE TITLE
Wire up app

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#6]
**Description**
Wire up app.

**Comment by modkaffes** [comment]
WIP [here](https://github.com/universelabs/universe-webapp/tree/feature/sign-up).

Needs a bit more work to be complete. I’ll update as I go.

**Comment by guylepage3** [comment]
Ok. Cool. Thanks @modkaffes this is priority one for sure. everything else does not matter much. 😄

**Comment by guylepage3** [comment]
@modkaffes I'm closing this issue.. Looks to be done. Great job! 😄
