### ISSUE TITLE
Learn React

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#64]
**Description**
@faddat I'm putting together a curriculum for you to assist with learning React and our front-end stack.

- [Mozilla JavaScript Guide](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Basics)

### Curriculum (React, Redux)
- [x] [Introducing React Hooks (Traversy Media (YouTube))](https://youtu.be/mxK8b99iJTg)
- [ ] [How to fetch data with React Hooks?](https://www.robinwieruch.de/react-hooks-fetch-data)

###  Curriculum (JavaScript)
[JavaScript Tutorials for Beginners 1–46 YouTube Playlist](https://www.youtube.com/playlist?list=PL4cUxeGkcC9i9Ae2D9Ee1RvylH38dKuET)

- [x] [JavaScript Tutorial for Beginners 01](https://youtu.be/qoSksQ4s_hg) - Introduction
- [x] [JavaScript Tutorial for Beginners 02](https://youtu.be/VB7y0yxZjro) - What is JavaScript?
- [x] [JavaScript Tutorial for Beginners 03](https://youtu.be/ranSYb-EhrU) - Hello World! in JavaScript
- [x] [JavaScript Tutorial for Beginners 04](https://youtu.be/czlwRUeTCgw) - Where to put your JS
- [x] [JavaScript Tutorial for Beginners 05](https://youtu.be/JzZFccCEgGA) - Google Chrome Developer Tools
- [x] [JavaScript Tutorial for Beginners 06](https://youtu.be/QLatPwsbDrQ) - Basic JavaScript Syntax & Rules
- [x] [JavaScript Tutorial for Beginners 07](https://youtu.be/u0Mq3FzpsmI) - JavaScript Variables
- [x] [JavaScript Tutorial for Beginners 08](https://youtu.be/_MC0Gw07w8M) - Basic Mathematical Operators
- [x] [JavaScript Tutorial for Beginners 09](https://youtu.be/Z1eV0RBRam0) - Math Operator Short-hand
- [x] [JavaScript Tutorial for Beginners 10](https://youtu.be/tH-q9QFNUdA) - Logging to the Console
- [x] [JavaScript Tutorial for Beginners 11](https://youtu.be/B4ZCFdrBmbE) - Booleans in JavaScript
- [x] [JavaScript Tutorial for Beginners 12](https://youtu.be/Lp-Du2fKoug) - If Statements
- [ ] [JavaScript Tutorial for Beginners 13](https://youtu.be/1v1Bk3Q02Sc) - Else If Statements
- [ ] [JavaScript Tutorial for Beginners 14](https://youtu.be/LjGaaWX_NbE) - Comparison Operators
- [ ] [JavaScript Tutorial for Beginners 15](https://youtu.be/mbT7sSmVUS8) - Logical Operators
- [ ] [JavaScript Tutorial for Beginners 16](https://youtu.be/PpbFyLTtpWI) - While Loops
- [ ] [JavaScript Tutorial for Beginners 17](https://youtu.be/U87UmD-5h4o) - for Loops
- [ ] [JavaScript Tutorial for Beginners 18](https://youtu.be/QSuTH0C_3_Y) - Break & Continue
- [ ] [JavaScript Tutorial for Beginners 19](https://youtu.be/eZBTLsv2ktM) - Practical Example using Loops
- [ ] [JavaScript Tutorial for Beginners 20](https://youtu.be/KH57lIgwe2g) - Functions
- [ ] [JavaScript Tutorial for Beginners 21](https://youtu.be/kjdZ1h3CIs4) - Variable Scope
- [ ] [JavaScript Tutorial for Beginners 22](https://youtu.be/TD3Pfuxgnuc) - Numbers
- [ ] [JavaScript Tutorial for Beginners 23](https://youtu.be/0ZiltZDg9Gg) - NaN (Not a Number)
- [ ] [JavaScript Tutorial for Beginners 24](https://youtu.be/k8MIbEVXhE0) - Strings
- [ ] [JavaScript Tutorial for Beginners 25](https://youtu.be/HEdikBHsMag) - Slice and Split Strings
- [ ] [JavaScript Tutorial for Beginners 26](https://youtu.be/EUnV-fCY0Pc) - Arrays
- [ ] [JavaScript Tutorial for Beginners 27](https://youtu.be/t-evBCCQFzM) - Introduction to Objects
- [ ] [JavaScript Tutorial for Beginners 28](https://youtu.be/wA5vU_HQfVI) - Creating a new JavaScript Object
- [ ] [JavaScript Tutorial for Beginners 29](https://youtu.be/yVdU2coJ1VQ) - THIS Keyword
- [ ] [JavaScript Tutorial for Beginners 30](https://youtu.be/SrhHszXkMRU) - Constructor Functions
- [ ] [JavaScript Tutorial for Beginners 31](https://youtu.be/irrxnH-nkqg) - The Date Object
- [ ] [JavaScript Tutorial for Beginners 32](https://youtu.be/H63dVFDuJDM) - What is the DOM in JavaScript?
- [ ] [JavaScript Tutorial for Beginners 33](https://youtu.be/SowaJlX1uKA) - Traversing the DOM
- [ ] [JavaScript Tutorial for Beginners 34](https://youtu.be/FQuwArzGPYo) - Changing Page Content
- [ ] [JavaScript Tutorial for Beginners 35](https://youtu.be/V0S0LXvnW-o) - Changing Element Attributes
- [ ] [JavaScript Tutorial for Beginners 36](https://youtu.be/97agDBCyxAE) - Changing CSS Styles
- [ ] [JavaScript Tutorial for Beginners 37](https://youtu.be/TrGI9Yki-24) - Adding Elements to the DOM
- [ ] [JavaScript Tutorial for Beginners 38](https://youtu.be/rBGgguNnutE) - Removing Elements from the DOM
- [ ] [JavaScript Tutorial for Beginners 39](https://youtu.be/bf_9IeihQ0M) - Introduction to JavaScript Events
- [ ] [JavaScript Tutorial for Beginners 40](https://youtu.be/XQEfWd1lh4Q) - The onClick Event
- [ ] [JavaScript Tutorial for Beginners 41](https://youtu.be/RVA4HoEE_q8) - Window onLoad Event
- [ ] [JavaScript Tutorial for Beginners 42](https://youtu.be/Az5J_EkhYCY) - JavaScript Timers
- [ ] [JavaScript Tutorial for Beginners 43](https://youtu.be/BhlvQfIaE4k) - Accessing form Elements
- [ ] [JavaScript Tutorial for Beginners 44](https://youtu.be/b0pxAb_yy2U) - VERY Simple form Validation
- [ ] [JavaScript Tutorial for Beginners 45](https://youtu.be/uq7omoxwA7A) - JavaScript Libraries
- [ ] [JavaScript Tutorial for Beginners 46](https://youtu.be/Qikr22Tc3wg) - What to Study Next

**Comment by guylepage3** [comment]
@faddat I've updated your curriculum for leaning React... Let me know if you have any questions. 👍

**Comment by guylepage3** [comment]
Hey @faddat I've just updated the list above. Please start at **Curriculum (React, Redux)**. Super cool that you're wanting to learn JavaScript and our front end tooling. 👍

**Comment by faddat** [comment]
Awesome, let's roll :D

**Comment by faddat** [comment]
Follow along as I slowly and painfully get the first tutorial 

https://github.com/faddat/reacthooks

**Comment by faddat** [comment]
@guylepage3 

Is NPM for the front-end also?  Thought it was just for back end stuff

https://www.robinwieruch.de/react-hooks-fetch-data

**Comment by faddat** [comment]
Reading:

https://www.robinwieruch.de/learn-react-js

**Comment by faddat** [comment]
Working through:

https://www.robinwieruch.de/react-hooks-fetch-data


https://github.com/faddat/react-hooks

**Comment by faddat** [comment]
Second hooks repo, using create-react-app

https://github.com/faddat/hooks2

**Comment by faddat** [comment]
Tabling hooks2 for a moment and headed down the list

**Comment by faddat** [comment]
Not making a new repo for every tutorial in JS for beginners, instead, updating with each updated file as a new commit.
