### ISSUE TITLE
Add copy to clipboard feature

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#9]
**Description**
Add copy to clipboard feature to secondary list items.

**Flow**
When the user is on their "dashboard" page and the users clicks on any of the secondary level list items, ie. Blockstack ID > Passphrase, the item is copied to the users clipboard so they may paste it into the appropriate field in a Blockstack app.

**Comment by modkaffes** [comment]
WIP [here](https://github.com/universelabs/universe-webapp/tree/feature/copy-to-clipboard).

Copy to clipboard works, what remains is to visually inform the user.

**Comment by guylepage3** [comment]
Working on adding a dropdown banner to this.

**Comment by guylepage3** [comment]
From Slack... https://universelabs.slack.com/archives/CH85A8S5S/p1560627417004200

Guy Lepage [3:36 PM]
Hey @modkaffes did you merge in your `feature/sign-up`?
Can I merge that in?

Guy Lepage [3:46 PM]
I will wait until this is merged before working on the `copy to clipboard`. Please let me know when you’ve merged and pushed to master @modkaffes 
I’m going to work on the deck and roadmap for a couple hours today.

**Comment by guylepage3** [comment]
New updates to the `copy to clipboard` functionality from today's [Weekly Scrum Call](https://github.com/universelabs/universe-operations2/issues/41).

Happy to take over this item. Working on this now.

**Comment by guylepage3** [comment]
Found a great resource https://codepen.io/zolash/pen/REQQrW

**Comment by guylepage3** [comment]
@modkaffes this is ready? We should be referencing issues in our git commit messages so that we can all see what's being worked on.. https://help.github.com/en/articles/autolinked-references-and-urls

**Comment by guylepage3** [comment]
Ahh. Just saw a random thread that it looks as though this is done. Taking a look now..

**Comment by guylepage3** [comment]
@modkaffes we're still getting the request to confirm copy to clipboard. Can we resolve this or is it part of the dependency?

<img width="451" alt="Screenshot 2019-06-18 16 39 40" src="https://user-images.githubusercontent.com/1711854/59718261-cdef5d80-91e7-11e9-8140-8b9b316bf191.png">

**Comment by guylepage3** [comment]
![copy-to-clipboard](https://user-images.githubusercontent.com/1711854/59723187-b5854000-91f3-11e9-851e-04a5dccda571.gif)
